(function(){
  const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
  const STATUS={normal:'正常上班',off:'休假',late:'晚到／晚上班',early:'提早下班',afternoon:'下半天',leave:'請假'};
  const EVENT={closed:'公休',spring:'春節',training:'教育課程',meeting:'半日會議',earlyClose:'提早打烊',noBooking:'不可預約日',specialOpen:'特殊營業日'};
  let db=null,notify=()=>{},staff=[],month='',selectedDate='',currentDate='',draft={exceptions:{}},events=[],monthUnsub=null,staffUnsub=null,annualUnsub=null,currentAnnualUnsub=null,monthSaveTimer=null,loadingMonth=false,monthRevision=0,monthDirty=false;
  const clone=value=>JSON.parse(JSON.stringify(value||{}));
  const esc=value=>String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
  const staffRef=()=>db.collection('salons').doc('default').collection('staff');
  const scheduleRef=value=>db.collection('salons').doc('default').collection('schedules').doc(value);
  const annualRef=year=>db.collection('salons').doc('default').collection('annualCalendars').doc(String(year));
  const activeStaff=()=>staff.filter(person=>person.active!==false).sort((a,b)=>a.role.localeCompare(b.role)||String(a.code).localeCompare(String(b.code),'zh-Hant',{numeric:true}));
  const roleLabel=role=>role==='technician'?'技術師':'設計師';
  const personLabel=person=>person.name||person.code;
  const monthDays=value=>new Date(Number(value.slice(0,4)),Number(value.slice(5,7)),0).getDate();
  const dateAt=day=>`${month}-${pad(day)}`;
  const entryAt=(date,id)=>draft.exceptions?.[date]?.[id]||{status:'normal',time:'',note:''};
  function ensureDate(date){draft.exceptions= draft.exceptions||{};draft.exceptions[date]=draft.exceptions[date]||{};return draft.exceptions[date]}
  function setEntry(date,id,value){const day=ensureDate(date);if(value.status==='normal'&&!value.note){delete day[id]}else day[id]=value;if(!Object.keys(day).length)delete draft.exceptions[date]}
  function statusShort(entry){if(entry.status==='late')return `${entry.time||''}到班`;if(entry.status==='early')return `${entry.time||''}下班`;if(entry.status==='afternoon')return `下半天${entry.time?' '+entry.time:''}`;return STATUS[entry.status]||''}
  function renderRoster(){for(const [role,target] of [['designer','scheduleDesigners'],['technician','scheduleTechnicians']]){$(target).innerHTML=activeStaff().filter(p=>p.role===role).map(p=>`<div class="rosterPerson"><b>${esc(p.code)}</b><span>${esc(p.name||'')}</span>${p.fixedOffDay!==null&&p.fixedOffDay!==undefined?`<small>固定週${'日一二三四五六'[p.fixedOffDay]}休</small>`:''}</div>`).join('')||'<small>尚無啟用人員</small>'}}
  function renderCalendar(){
    if(!month)return;const [year,mon]=month.split('-').map(Number),first=new Date(year,mon-1,1).getDay(),days=monthDays(month),cells=[];
    for(let i=0;i<first;i++)cells.push('<div class="monthDay outside"></div>');
    for(let day=1;day<=days;day++){const date=dateAt(day),entries=draft.exceptions?.[date]||{},dayEvents=events.filter(event=>event.date===date);const lines=activeStaff().filter(p=>entries[p.id]).map(p=>{const entry=entries[p.id];return `<span class="scheduleMark status-${esc(entry.status)}">${esc(personLabel(p))}${entry.status==='off'||entry.status==='leave'?'':` ${esc(statusShort(entry))}`}</span>`}).join('');const badges=dayEvents.map(event=>`<span class="calendarEvent event-${esc(event.type)}">${esc(event.title||EVENT[event.type])}</span>`).join('');cells.push(`<button class="monthDay ${date===selectedDate?'selected':''}" data-date="${date}"><b>${day}</b>${badges}${lines}</button>`)}
    $('monthCalendar').innerHTML=cells.join('');document.querySelectorAll('.monthDay[data-date]').forEach(cell=>cell.onclick=()=>selectDate(cell.dataset.date));
  }
  function statusOptions(selected){return Object.entries(STATUS).map(([value,label])=>`<option value="${value}" ${value===selected?'selected':''}>${label}</option>`).join('')}
  function renderEditor(){
    if(!selectedDate){$('selectedScheduleDate').textContent='請選擇日期';$('dayScheduleRows').innerHTML='';return}
    $('selectedScheduleDate').textContent=selectedDate;$('annualDayEvents').innerHTML=events.filter(e=>e.date===selectedDate).map(e=>`<span>${esc(EVENT[e.type])}：${esc(e.title||EVENT[e.type])}</span>`).join('');
    $('dayScheduleRows').innerHTML=['designer','technician'].map(role=>`<section class="dayRole"><h4>${roleLabel(role)}</h4>${activeStaff().filter(p=>p.role===role).map(p=>{const entry=entryAt(selectedDate,p.id),timed=['late','early','afternoon'].includes(entry.status);return `<div class="dayScheduleRow" data-staff-id="${esc(p.id)}"><input type="checkbox" class="schedulePick" title="多人快速設定"><span><b>${esc(p.code)}</b> ${esc(p.name||'')}</span><select class="scheduleStatus">${statusOptions(entry.status)}</select><input type="time" class="scheduleTime" value="${esc(entry.time||'')}" ${timed?'':'disabled'}><input class="scheduleNote" value="${esc(entry.note||'')}" placeholder="備註"></div>`}).join('')}</section>`).join('');
    document.querySelectorAll('.scheduleStatus,.scheduleTime,.scheduleNote').forEach(control=>control.onchange=()=>updateRow(control.closest('.dayScheduleRow')));
  }
  function updateRow(row){const status=row.querySelector('.scheduleStatus').value,time=row.querySelector('.scheduleTime'),note=row.querySelector('.scheduleNote').value.trim();time.disabled=!['late','early','afternoon'].includes(status);if(time.disabled)time.value='';setEntry(selectedDate,row.dataset.staffId,{status,time:time.value,note});renderCalendar();queueMonthSave()}
  function selectDate(date){selectedDate=date;renderCalendar();renderEditor()}
  function selectMonth(value){clearTimeout(monthSaveTimer);monthRevision++;monthDirty=false;month=value;$('scheduleMonth').value=value;selectedDate=`${value}-01`;if(monthUnsub)monthUnsub();if(annualUnsub)annualUnsub();if(!db){draft={exceptions:{}};events=[];renderAll();return}loadingMonth=true;$('monthSaveState').textContent='讀取中…';monthUnsub=scheduleRef(value).onSnapshot(doc=>{if(monthDirty&&!loadingMonth)return;draft=clone(doc.data()||{exceptions:{}});loadingMonth=false;$('monthSaveState').textContent='已同步';renderAll()},error=>{loadingMonth=false;$('monthSaveState').textContent='讀取失敗';notify('月排班讀取失敗：'+error.message,true)});annualUnsub=annualRef(value.slice(0,4)).onSnapshot(doc=>{events=doc.data()?.events||[];renderAll()},error=>notify('年度行事曆讀取失敗：'+error.message,true))}
  function renderAll(){renderRoster();renderCalendar();renderEditor()}
  function shiftMonth(amount){const [year,mon]=month.split('-').map(Number),date=new Date(year,mon-1+amount,1);selectMonth(`${date.getFullYear()}-${pad(date.getMonth()+1)}`)}
  function applyFixedOff(){for(const person of activeStaff().filter(p=>p.role==='designer'&&p.fixedOffDay!==null&&p.fixedOffDay!==undefined)){for(let day=1;day<=monthDays(month);day++){const date=dateAt(day),hasOverride=Object.prototype.hasOwnProperty.call(draft.exceptions?.[date]||{},person.id);if(new Date(`${date}T12:00:00`).getDay()===Number(person.fixedOffDay)&&!hasOverride)setEntry(date,person.id,{status:'off',time:'',note:'固定休'})}}renderAll();queueMonthSave();notify('固定休已套用並自動同步，可直接改任一天為上班。')}
  async function copyPrevious(){if(!db)return;const [year,mon]=month.split('-').map(Number),previous=new Date(year,mon-2,1),key=`${previous.getFullYear()}-${pad(previous.getMonth()+1)}`,doc=await scheduleRef(key).get(),source=doc.data()?.exceptions||{},next={};for(const [date,entries] of Object.entries(source)){const day=Number(date.slice(-2));if(day<=monthDays(month))next[dateAt(day)]=clone(entries)}draft={exceptions:next};renderAll();queueMonthSave();notify(`已複製 ${key} 並自動同步。`)}
  async function saveMonth(){if(!db||loadingMonth){if(!db)notify('Firebase 尚未連線。',true);return}const state=$('monthSaveState'),revision=monthRevision,payload=clone(draft.exceptions||{});try{state.textContent='同步中…';await scheduleRef(month).set({exceptions:payload,updatedAtMs:Date.now()});if(revision===monthRevision){monthDirty=false;state.textContent='已同步'}}catch(error){state.textContent='同步失敗';notify('排班儲存失敗：'+error.message,true)}}
  function queueMonthSave(){clearTimeout(monthSaveTimer);monthRevision++;monthDirty=true;$('monthSaveState').textContent='等待同步…';monthSaveTimer=setTimeout(saveMonth,450)}
  function clearMonth(){if(!confirm(`確定清除 ${month} 全部例外排班？`))return;draft={exceptions:{}};renderAll();queueMonthSave()}
  function exportMonth(){const rows=['日期,職類,編號,姓名,狀態,時間,備註'];for(const [date,entries] of Object.entries(draft.exceptions||{})){for(const [id,entry] of Object.entries(entries)){const p=staff.find(item=>item.id===id);rows.push([date,roleLabel(p?.role),p?.code||id,p?.name||'',STATUS[entry.status],entry.time||'',entry.note||''].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))}}const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${month}-排班.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
  function quickStatus(status){const picked=[...document.querySelectorAll('.dayScheduleRow')].filter(row=>row.querySelector('.schedulePick').checked);if(!picked.length){notify('請先勾選要快速設定的人員。',true);return}for(const row of picked){row.querySelector('.scheduleStatus').value=status;updateRow(row)}renderEditor()}
  function nextDay(){if(!selectedDate)return;const date=new Date(`${selectedDate}T12:00:00`);date.setDate(date.getDate()+1);const next=`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;if(next.slice(0,7)===month)selectDate(next)}
  function open(){const current=$('dateInput')?.value?.slice(0,7)||new Date().toISOString().slice(0,7);$('scheduleModal').classList.add('open');selectMonth(current)}
  function openAnnual(){const year=Number(month?.slice(0,4)||new Date().getFullYear());$('annualYear').value=year;$('annualDate').value=`${year}-01-01`;$('annualCalendarModal').classList.add('open');listenAnnualEditor()}
  function listenAnnualEditor(){if(annualUnsub)annualUnsub();if(!db){events=[];renderAnnual();return}const year=$('annualYear').value;annualUnsub=annualRef(year).onSnapshot(doc=>{events=doc.data()?.events||[];renderAnnual()},error=>notify('年度行事曆讀取失敗：'+error.message,true))}
  function renderAnnual(){$('annualEventList').innerHTML=events.length?events.sort((a,b)=>a.date.localeCompare(b.date)).map(event=>`<div class="annualEvent"><time>${esc(event.date)}</time><b>${esc(EVENT[event.type])}</b><span>${esc(event.title||'')}</span><button class="danger" data-delete-event="${esc(event.id)}">刪除</button></div>`).join(''):'<div class="hint">本年度尚未設定事件。</div>';document.querySelectorAll('[data-delete-event]').forEach(button=>button.onclick=()=>saveAnnual(events.filter(e=>e.id!==button.dataset.deleteEvent)))}
  async function saveAnnual(next){if(!db){notify('Firebase 尚未連線，無法儲存年度行事曆。',true);return}try{await annualRef($('annualYear').value).set({events:next,updatedAtMs:Date.now()});notify('年度行事曆已同步。')}catch(error){notify('年度行事曆儲存失敗：'+error.message,true)}}
  function addAnnual(){const date=$('annualDate').value,type=$('annualType').value,title=$('annualTitle').value.trim();if(!date||date.slice(0,4)!==String($('annualYear').value)){notify('請選擇同年度的日期。',true);return}saveAnnual([...events,{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date,type,title}]);$('annualTitle').value=''}
  function connect(database){db=database;if(staffUnsub)staffUnsub();staffUnsub=staffRef().onSnapshot(snapshot=>{staff=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));renderAll()},error=>notify('排班人員讀取失敗：'+error.message,true))}
  function setCurrentDate(date){currentDate=date;if(currentAnnualUnsub)currentAnnualUnsub();if(!db||!date)return;currentAnnualUnsub=annualRef(date.slice(0,4)).onSnapshot(doc=>{const dayEvents=(doc.data()?.events||[]).filter(event=>event.date===currentDate),box=$('todayEvents');box.hidden=!dayEvents.length;box.innerHTML=dayEvents.map(event=>`<span><b>${esc(EVENT[event.type])}</b> ${esc(event.title||'')}</span>`).join('')},error=>notify('今日行事曆讀取失敗：'+error.message,true))}
  function init(options={}){notify=options.notify||notify;$('scheduleClose').onclick=()=>$('scheduleModal').classList.remove('open');$('monthPrev').onclick=()=>shiftMonth(-1);$('monthNext').onclick=()=>shiftMonth(1);$('scheduleMonth').onchange=event=>selectMonth(event.target.value);$('applyFixedOff').onclick=applyFixedOff;$('copyPreviousMonth').onclick=copyPrevious;$('clearMonthSchedule').onclick=clearMonth;$('exportMonth').onclick=exportMonth;$('saveMonthSchedule').onclick=saveMonth;$('nextScheduleDay').onclick=nextDay;document.querySelectorAll('[data-quick-status]').forEach(button=>button.onclick=()=>quickStatus(button.dataset.quickStatus));$('annualClose').onclick=()=>$('annualCalendarModal').classList.remove('open');$('annualYear').onchange=()=>{$('annualDate').value=`${$('annualYear').value}-01-01`;listenAnnualEditor()};$('addAnnualEvent').onclick=addAnnual}
  window.SalonSchedule={init,connect,open,openAnnual,setCurrentDate};
})();
